fun main() {

    val ork = Ork()
    val barde = Barde()
    val zwerg = Zwerg()
    val boss = Boss()
    var bossHelfer = Bosshelfer()



    println("-----Die tapferen Helden-----")
    println()
    Thread.sleep(2500)
    ork.kampfSchrei()
    println()
    Thread.sleep(2500)
    barde.kampfSchrei()
    println()
    Thread.sleep(2500)
    zwerg.kampfSchrei()
    println()
    Thread.sleep(2500)
    println("------------------------------")
    println()
    println("Der Endboss -> Fluffi <- ist aufgetaucht")
    Thread.sleep(2500)
    println()
    println("...ein dreiköpfiger übergroßer Hund der Hölle!!!")
    Thread.sleep(2500)
    println()
    println("Fluffi fletscht mit den Zähnen....")
    println("-------------------------------")
    Thread.sleep(2500)
    println("Fluffi macht sich kampfbereit...")
    Thread.sleep(2500)
    println("DER KAMPF BEGINNT !!!")
    println("-------------------------------")



    ork.normalerAngriffOrk(boss)
    Thread.sleep(2500)
    zwerg.normalerAngriffZwerg(boss)
    Thread.sleep(2500)
    boss.angreifen(ork)
    Thread.sleep(2500)
    ork.selbstHeilen(ork)
    Thread.sleep(2500)
    boss.angreifen(ork)
    Thread.sleep(2500)
    ork.blocken(ork,boss)
    Thread.sleep(2500)
    ork.schildStoß(boss)
    Thread.sleep(2500)
    zwerg.blutungZwerg(boss)
    Thread.sleep(2500)
    zwerg.schwererAngriffZwerg(boss)
    Thread.sleep(2500)
    zwerg.lebensRaubZwerg(zwerg,boss)
}